kind: Service
apiVersion: v1
metadata:
  name: webapp-loadbalancer-https
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "ea983a0e-59ad-48da-b3ce-dd593e977c9e"
spec:
  type: LoadBalancer
  selector:
    app: webapp-service
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
