apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-explore
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: explore
            image: dimonra13/groovyscript:v1
            imagePullPolicy: Always
          restartPolicy: Never
