apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  selector:
    matchLabels:
      app: recommender
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recommender
    spec:
      containers:
      - image: dimonra13/recommender:v1
        imagePullPolicy: Always
        name: recommender
        ports:
        - containerPort: 8011
          name: recommender
        resources:
          limits:
            cpu: "2000m"
            memory: "13Gi"
          requests:
            cpu: "1250m"
            memory: "11Gi"
