apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: web-app
      image: dimonra13/appwebtfg:v1
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: mysql
      image: dimonra13/mysql:v1
      ports:
	- name: dbport
	  containerPort: 3306
